logging:
  level:
    root: error
    com.plantserver: error
spring:
  redis:
    host: localhost
    port: 6379
    password:
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
  influx:
    url: http://60.205.207.115:8086
    user: root
    password: root
  mqtt:
    url: tcp://60.205.207.115:1883
    client:
      consumer_id: pla_consumer
      producer_id: pla_producer
    default:
      topic: HPtopic/#,byteMsgTest/#
      msgTopic: byteMsgTest/#
    completionTimeout: 3000
    username: admin
    password: public