plantsever:
  uploadPath: /var/lib/influx/data
  username: admin
  password: 
  sysname: 
  corpname: 
logging:
  level:
    root: error
    com.plantserver: debug
spring:
  redis:
    host: localhost
    port: 
    password:
    # 连接超时时间（毫秒）
    timeout: 
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 
        # 连接池中的最小空闲连接
        min-idle: 
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 
  influx
    url: http://127.0.0.1:8086
    user: 
    password: 
