server:
  #session-timeout: 1800
  #    tomcat:
  #        max-threads: 1000
  #        min-spare-threads: 30
  port: 9998
logging:
  level:
    root: error
    com.plantserver: info
spring:
  redis:
    host: localhost
    port: 6379
    password: public
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
  influx:
    url: http://localhost:8086
    user: root
    password: root
    database1: plantsurv_realTime
    database2: plantsurv_perHour
    measurement:
      shake: shake
      temperature: temperature
      power: power
  mqtt:
    url: tcp://localhost:1883
    client:
      consumer_id: pla_consumer
      producer_id: pla_producer
    default:
      subtopic: safercon/JSTG
      pubTopic: safercon/test
    completionTimeout: 3000
    username: admin
    password: public
