
# yaml 配置实例
version: '3.4'
services:
  mqtt:
    restart: always
    image: emqx/emqx
    container_name: emqx
    ports:
      - "1883:1883"
      - "18083:18083"
      - "9001:9001"
    volumes:
     # - ./config:/etc
      - ./log:/opt/emqx/log
    environment:
      - TZ=Asia/Shanghai
      - EMQX_LOG__LEVEL=notice
      - EMQX_NAME=raspberry
  redis:
    restart: always
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  edge:
    build: .
    restart: always
    container_name: edge
    links:
      - redis
      - mqtt
    volumes:
      - ./log:/home/app/log
    environment:
      - TZ=Asia/Shanghai
